### ISSUE TITLE
Flutter 2.5 Warning when building: Deprecated Version of Android embedding

### ISSUE THREAD

**Issue by danielRi** [4itworks/opensource_qwkin_dart#15]
When building app that depends on torch_controller plugin, using latest flutter 2.5, the following warning is printed:

```The plugins `flutter_ringtone_player, system_settings` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider
removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.```

Plugin needs to be migrated to V2 embedding.

**Comment by csgulati09** [comment]
When do you plan to migrate it?

**Comment by i-am-ijaz** [comment]
Facing the same issue 

The plugin `torch_controller` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by T1960CT** [comment]
Bump this issue... If I knew more about flutter, I'd contribute, but I'm fairly new to it.

**Comment by WilliamCunhaCardoso** [comment]
Looks like this pr solves it https://github.com/4itworks/opensource_qwkin_dart/pull/16

**Comment by lovelessX** [comment]
Can we get a release built for this version?
